# Generated by Django 4.2.2 on 2023-07-10 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tweet", "0006_alter_tweetmodel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweetmodel",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="tweet_user",
                through="tweet.TweetLike",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
