# Generated by Django 4.2.2 on 2023-06-29 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tweet", "0004_tweetmodel_timestamp_tweetlike_tweetmodel_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweetmodel",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tweet.tweetmodel",
            ),
        ),
    ]
