# Generated by Django 4.2.2 on 2023-07-11 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0002_profile_followers_profile_timestamp_profile_updated_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="link",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.URLValidator(
                        code="Invalid link", message="Invalid link"
                    )
                ],
            ),
        ),
    ]
